version: "3"
services:
  app:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    command: npm run start
    environment:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - PORT=3000
      - JWT_ACCESS_TOKEN=${JWT_ACCESS_TOKEN}
      - ADMIN_SECRET_KEY=${ADMIN_SECRET_KEY}


  postgres:
    image: postgres
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db